name: managementMetadataFromRS
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - alabaster
  - asn1crypto
  - atk
  - atomicwrites
  - attrs
  - babel
  - blas
  - boost-cpp
  - bzip2
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - chardet
  - cryptography
  - curl
  - cycler
  - dbus
  - docutils
  - expat
  - ffmpeg
  - fontconfig
  - freetype
  - freexl
  - fribidi
  - gdal
  - gdk-pixbuf
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - gmp
  - gnutls
  - gobject-introspection
  - graphite2
  - gst-plugins-base
  - gstreamer
  - gtk2
  - harfbuzz
  - hdf4
  - hdf5
  - icu
  - idna
  - imagesize
  - importlib_metadata
  - jasper
  - jinja2
  - jpeg
  - json-c
  - kealib
  - kiwisolver
  - krb5
  - lame
  - libblas
  - libcblas
  - libcurl
  - libdap4
  - libedit
  - libffi
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libiconv
  - libkml
  - liblapack
  - liblapacke
  - libnetcdf
  - libopenblas
  - libpng
  - libpq
  - libspatialite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libwebp
  - libxcb
  - libxml2
  - lz4-c
  - markupsafe
  - matplotlib
  - matplotlib-base
  - more-itertools
  - ncurses
  - nettle
  - numpy
  - openblas
  - opencv
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pango
  - pcre
  - pip
  - pixman
  - pluggy
  - poppler
  - poppler-data
  - postgresql
  - proj4
  - pthread-stubs
  - py
  - pycparser
  - pygments
  - pyopenssl
  - pyparsing
  - pyqt
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-fmask
  - pytz
  - qt
  - readline
  - requests
  - rios
  - scipy
  - setuptools
  - sip
  - six
  - snowballstemmer
  - sphinx
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml
  - sphinxcontrib-websupport
  - sqlite
  - tbb
  - tiledb
  - tk
  - tornado
  - tzcode
  - urllib3
  - wcwidth
  - wheel
  - x264
  - xerces-c
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zipp
  - zlib
  - zstd

